### ISSUE TITLE
Allow access to parameters

### ISSUE THREAD

**Issue by keniwhat** [vapor/routing-kit#120]
It is normal for a web framework to allow access to the request parameters without knowing the expected names of the parameters.  RoutingKit.Parameters does not allow accessing  parameters without knowing their names. 
 
A list of the parameter names could be returned from Parameters. Then the client code can query for the value of the parameter.

I would consider this standard behaviour for a web-container and vapor to be non-standard.

This restriction is preventing vapor from being dropped in as a replacement web container for our current solution.

**Comment by vzsg** [comment]
Have you seen [catchAll](https://docs.vapor.codes/basics/routing/#catchall)? The documentation sure is lacking, but if you use that, you can access all parameters as a String array using `req.parameters.getCatchall()`.

**Comment by vzsg** [comment]
Well yes, as written on the tin, this collects parameters that were matched by `**`, not by named parameters. Since you apparently don't want to assign names to the parameters, this could be the way out: a route that ends with a catchall.

---

But could you provide an example scenario where you have named parameters but don't want to have named parameters at the same time? That's getting harder to imagine the more I think about it.

**Comment by keniwhat** [comment]
Here is an URL:  http://192.168.1.24/api/product/:type/mediatype/:mediatype
Typically I would expect to be able to get a list of all paramaters and then using the names, collect the values and return them in a map.
My framework abstracts away the Web Container implementation and is URL-agnostic. I see no point in preventing the parameters from being picked up without knowing their names. Of course, further downstream something must know their names, but at the lower level it should not be enforced. No other framework I ever used did this.
But anyway ... I have implemented a workaround.  It's awkward now, not impossible.

**Comment by gwynne** [comment]
@vzsg I don't think it's too unreasonable to make the list of matched parameter names available. I would suggest adding a property of this sort to `Parameters`:

```swift
#if swift(>=5.7) // SE-0346
    public var allNames: some Collection<String> { self.values.keys }
#else
    public var allNames: some Collection { self.values.keys }
#endif
```

**Comment by gwynne** [comment]
@keniwhat For the record, Vapor is not "enforcing" a lack of access to this information. It just hadn't occurred to anyone to make it available, and basic design principles of encapsulation say only make public what needs to be (though certainly Vapor is rather spotty in that regard) - and apparently it hasn't been a sufficiently significant concern for anyone to bother asking after it until now. I've opened a PR to resolve the missing functionality.
