### ISSUE TITLE
Avoid print in TrieRouter.swift

### ISSUE THREAD

**Issue by Frizlab** [vapor/routing-kit#125]
**Is your feature request related to a problem? Please describe.**
Yes.
I purposefully override a route because I want to handle some `HEAD` requests manually, but also want to handle the `GET` requests for the same path.
When a `GET` route is registered, the default responder in Vapor will also register the corresponding `HEAD` route (if the path components are static, which is my case).

Every time the server launches, I get a warning _printed_: `[Routing] Warning: Overriding route output at: HEAD/…`.
This is 1/ annoying, but I’d be fine with it, but 2/ problematic as the print does not use the logger I have configured. If I use a structured logger to be able to parse the logs, I get this line out of nowhere which is unparseable (I can deal but it’s not great).

**Describe the solution you'd like**
The message should be logged using a logger, w/ a log level set to `notice` presumable, or even `debug` (it’s important to know, but not a warning IMHO, because overriding a route can be normal, as it is in my case).

**Describe alternatives you've considered**
Vapor could let the client decide whether the `HEAD` route should be registered for a given `GET` route; or even just not register it at all.
This would allow me to avoid having the warning, though it would not fix the fact that logging w/o a logger is a bad practice.

**Additional context**
N/A

**Comment by gwynne** [comment]
@0xTim Yep, we still have an actual `print()` hanging around after all this time 😕 I don't see a good way to get a `Logger` passed into this logic without breaking public API, any thoughts?

**Comment by 0xTim** [comment]
We can pass in a logger with a default logger that does nothing (similar to how Soto does it)

**Comment by gwynne** [comment]
Okay, I'll work up a PR for both repos
