### ISSUE TITLE
Integrate SwiftLint

### ISSUE THREAD

**Issue by twof** [vapor/routing-kit#56]
Should follow the rules laid out in https://github.com/vapor/vapor/pull/1876 and automatically apply fixes when possible.

Should also be part of CI.

**Comment by tanner0101** [comment]
We're currently using async-kit as a test bed for GH integrations. If anyone wants to PR a swift lint CI workflow there I'd be happy to accept. Closing the issue here since it's not related to routing and more of a general vapor maintainer issue.
