### ISSUE TITLE
Not working with localhost

### ISSUE THREAD

**Issue by grosch** [vapor/routing-kit#88]
Looks like when I add a grouping Vapor stop allowing "localhost" and I have to explicitly say 127.0.0.1

```bash
[griffon:/tmp] scott% curl localhost:8080/clients/test
{"error":true,"reason":"Not Found"}
[griffon:/tmp] scott% curl 127.0.0.1:8080/clients/test
1
[griffon:/tmp] scott% ping localhost
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.062 ms
^C
--- localhost ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.062/0.062/0.062/0.000 ms
```

[bug.zip](https://github.com/vapor/routing-kit/files/4308215/bug.zip)

**Comment by tanner0101** [comment]
I can't download `bug.zip` for some reason. Could you paste the code snippet you're using here?

**Comment by grosch** [comment]
```swift
func routes(_ app: Application) throws {
    let clients = app.grouped("clients")
    let clientController = ClientController()
    clients.get("test", use: clientController.test)
}

struct ClientController {
    public func test(req: Request) throws -> EventLoopFuture<Int> {
        return req.eventLoop.makeSucceededFuture(1)
    }
}
```

**Comment by grosch** [comment]
So I'm seeing that a GET will work with `localhost:8080`, but when I do a `PATCH` I have to use `127.0.0.1:8080`.  Not sure if that helps at all on debugging this, @tanner0101 ?

**Comment by tanner0101** [comment]
@grosch hmm. Maybe that's something weird with `curl`? Vapor 4 binds to `127.0.0.1` by default but I always use `localhost` when testing and it works fine. I use https://httpie.org on the command line though.

**Comment by grosch** [comment]
This seems like it was a transient issue that a reboot has fixed....I'm going to close and if I'm having it again, we'll look deeper.
