### ISSUE TITLE
Have to name all params the same

### ISSUE THREAD

**Issue by grosch** [vapor/routing-kit#90]
The routing engine is too restrictive on what the parameter fields can be.  For example, I tried to create these two routes for a DELETE

orders/:id
orders/:orderID/work/:workID

That fails because the router wants the ':orderID' in the second line to also be called ':id'.  

Yes, I can do that of course, but it makes the names not as clear when working with multiple fields.

**Comment by tanner0101** [comment]
This is a duplicate of #92
