### ISSUE TITLE
Extraneous slashes and empty path components

### ISSUE THREAD

**Issue by tanner0101** [vapor/routing-kit#98]
RoutingKit should ensure paths do not contain slashes nor empty path components.

**Comment by tanner0101** [comment]
Moving https://github.com/vapor/vapor/pull/2362 here.

**Comment by gwynne** [comment]
Closing this due to it being another of Tanner's many open "I was gonna get around to it eventually but no one has complained and there's been no attention paid for ages" issues on various repos 🙂 I'm happy to reopen it if anyone feels it needs addressing in the present day.
